### ISSUE TITLE
Scenes in the outline are opened at save

### ISSUE THREAD

**Issue by TipiT** [piersdeseilligny/betterfountain#96]
The Outline tool is great, btw, but there is an annoying feature in it - it always shows the scenes opened. One can close an #act, a ##sequence, or a ###scene but when **any scene text** is edited (not the header itself!) and the project saved, the outline tool is reloaded/updated and the scenes are visible again (the scenes are opened).

One might call this a feature, but for my opinion the user should be able to decide when and which Acts, Sequences, or Scenes are closed in the Outline tool.

<img width="300" alt="Screenshot 2020-12-03 at 15 16 47" src="https://user-images.githubusercontent.com/1223414/101034049-a1b1d300-357a-11eb-9526-d94add2722fd.png">

<img width="294" alt="Screenshot 2020-12-03 at 15 14 55" src="https://user-images.githubusercontent.com/1223414/101034068-a37b9680-357a-11eb-9060-37178c497662.png">

**Comment by piersdeseilligny** [comment]
Fixed as part of 1.7.2 👍

**Comment by TipiT** [comment]
For me it works only for #ACTS, so acts stay closed or open. But ##SEQUENCES and ###SCENES still gets opened when saving.

**Comment by daryluren** [comment]
I've managed to replicate it by holding a key down (as in typing the same letter into the script super quickly). I suspect it's due to certain events firing over one another. I will continue investigating.

**Comment by piersdeseilligny** [comment]
@TipiT I've just released 1.8.0, which includes Daryl's fix. Could you let me know if it works as expected for you? It seems fixed for me on my side of things.

**Comment by TipiT** [comment]
It works - almost perfectly!

#Acts and ##Sequences stay closed after saving, so that is all good.

###Scenes seem to opened randomly, but there are not many situations where the user wants to close scenes, because the sequence should fit easily onto the screen.

Definitely a huge improvement and I will keep testing a while and let you know to a new ticket if there are use cases to make this even better. Thank you very much, guys!
